/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent.of.code

class App {
    val greeting: String
        get() {
            return "Ups! Solutions are in `app/src/test/kotlin/advent.of.code` directory!"
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
}
